services:
  telegram-proxy:
    build: .
    container_name: telegram-proxy
    restart: always
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - PROXY_HOST=gate.node-proxy.com
      - PROXY_PORT=10000
      - PROXY_USER=api6427e610fa202b13_c_US_s_1
      - PROXY_PASS=aepKxOZdTRMDH3XC
      - NODE_ENV=production
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true